### ISSUE TITLE
Do not use in-sources ispc, use external ispc

### ISSUE THREAD

**Issue by ghost** [Vertexwahn/rules_oidn#10]
~At least initially, until #1 is fixed,~ drop the build-in ispc (`ispc_cc_library`)  and rely on an externally install ispc (as documented within 

https://github.com/OpenImageDenoise/oidn#prerequisites

**Comment by Vertexwahn** [comment]
https://github.com/Vertexwahn/rules_oidn/issues/1 was solved

**Comment by ghost** [comment]
@Vertexwahn , this issue is general, still valid in context of #5 / #13
