### ISSUE TITLE
Change rules_ispc repo back to Vertexwahn

### ISSUE THREAD

**Issue by ghost** [Vertexwahn/rules_oidn#14]
https://github.com/Vertexwahn/rules_oidn/blob/b0518fe80da25636a5919e82fe5a90ef916ebf32/third_party/oidn/oidn.bzl#L97-L102

**Comment by Vertexwahn** [comment]
@abebeos Done!

**Comment by ghost** [comment]
fixed within https://github.com/Vertexwahn/rules_oidn/commit/f1d7bd2e4163fe671111166da2479bd3b9ae2678#
