### ISSUE TITLE
Cleanup README

### ISSUE THREAD

**Issue by ghost** [Vertexwahn/rules_oidn#15]
- remove bug description
- consider removal of https://github.com/Vertexwahn/rules_oidn#other-projects-related-to-this

## Most Important

* State clearly that the current status of the `rules_oidn` does not produce a result compatible to the cmake build
* mention the main differences of the build

**Comment by Vertexwahn** [comment]
I would consider this as done.

**Comment by ghost** [comment]
Yeah, its fine!
