### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by Vertexwahn** [Vertexwahn/rules_oidn#2]
macOS build does currently not work since oneDNN build must be modified here a bit...

**Comment by ghost** [comment]
just as a sidenote: A bazel build (within the oidn source-tree, as suggested within #13) similar to the cmake build should(!) be mac compatible (as oidn supports mac):

https://github.com/OpenImageDenoise/oidn#compiling-on-linuxmacos)

**Comment by Vertexwahn** [comment]
I try currently to get it working on macOS with M1 processor. The current problem is within compiling `@compute_library//:arm_compute`

```
bazel build --config=macos @compute_library//:arm_compute
```

Therefore I had a look at https://github.com/ARM-software/ComputeLibrary which comes lukily with experimental Bazel support - `bazel build //:arm_compute` results in this repo also with errors. One problem is that it expects OpenMP support. As far as I understand it until now Apple Clang does not come with OpenMP support. Not sure what direction to go here - try to exclude OpenMP support or install on macOS a compiler that can handle OpenMP...

My approach to exclude OpenMP:

```
maybe(
        git_repository,
        name = "compute_library",
        remote = "https://github.com/Vertexwahn/ComputeLibrary.git",
        commit = "47bf1d923d61a315c5f4ecdd86528719bb40d649",
    )
```

**Comment by ghost** [comment]
Just remembrr 2.0 is coming (https://github.com/Vertexwahn/rules_oidn/issues/13#issuecomment-1474840510), possibly with M1 support

**Comment by Vertexwahn** [comment]
It seems that I fixed now compiling of ComputeLibrary (with some hacks -> https://github.com/Vertexwahn/ComputeLibrary/commits/apple-clang-support). I had to downgrade to C++14 since for some stupid reason the identifier `requires` seems to be used which breaks modern C++.

When I run now in the test folder (on macOS with M1):

```
bazel build --config=macos --keep_going //:example 
```

I get the following errors:

```
external/mkl_dnn_acl_compatible/src/cpu/jit_utils/jit_utils.cpp:33:10: fatal error: 'common/ittnotify/jitprofiling.h' file not found
#include "common/ittnotify/jitprofiling.h"
```

and

```
external/oidn/core/cpu_device.cpp:19:38: error: use of undeclared identifier 'ISA'
    tensorBlockSize = isISASupported(ISA::AVX512_CORE) ? 16 : 8;
```

It seems that the enum ISA is only available when compiling with x64, but when on ARM and using oneDNN this code path is also hit:
https://github.com/OpenImageDenoise/oidn/blob/d959bac5b7130b31c41095811ddfbe58c4cf03f4/core/cpu_device.cpp#L19

Seems that there needs to be something fixed/patched on OIDN to get macOS M1 with oneDNN working here.

**Comment by ghost** [comment]
You're placing yourself into a maintenance hell. 

Wait for an answer to this, possibly the better choice is to wait: https://github.com/OpenImageDenoise/oidn/issues/156#issuecomment-1477568708

**Comment by Vertexwahn** [comment]
Initially, I was running here in the wrong direction. I was thinking that the macOS version of OIDN 1.4.3 is also using oneDNN. Therefore, I tried to fix this code path. E.g. fixing ComputeLibrary OpenMP issues with the use of Apple Clang, come up with a macOS build OneDNN, or try to fix `isISASupported(ISA::AVX512_CORE) `issue in OIDN. Finally, I found out that ODIN 1.4.3 uses on macOS BNNS as a neural runtime. Something that I could have figured out quite earlier, but anyway finally I found it out. My hope is that the BNNS path can be bazelized straight forward. I tried it using CMake on macOS M1 and it worked out of the box.

**Comment by ghost** [comment]
One gets easily lost in the build jungle. So one reason more for

- https://github.com/Vertexwahn/rules_oidn/issues/13

**Comment by Vertexwahn** [comment]
I have already a working version of rules_oidn for macOS M1 on my machine - need to change it in a way not to break Windows + Ubuntu builds

**Comment by Vertexwahn** [comment]
If you want to use these rules on macOS you simply need to modify the `oidn.BUILD` file:

COMMON_DEFINES = [
    "OIDN_DNNL",  # change this to OIDN_BNNS for macOS
    "OIDN_STATIC_LIB",
    "OIDN_FILTER_RT",
    "OIDN_FILTER_RTLIGHTMAP",
]

This still needs to be done manually sicne ispc_cc_library is a macro and cannot resolve selects to support different operating systems [here](https://stackoverflow.com/questions/75827650/how-to-work-around-select-is-not-iterable-in-a-macro). More details here. [rules_ispc](https://github.com/Vertexwahn/rules_ispc) has to be improved [here](https://stackoverflow.com/questions/75828030/how-to-convert-a-macro-that-invokes-native-genrule-and-native-cc-library-to-a-ru) first (details here)

**Comment by Vertexwahn** [comment]
oidn_rules work now on macOS Intel and arm64 (e.g. M1)
