### ISSUE TITLE
Test/Reproducer not working

### ISSUE THREAD

**Issue by ghost** [Vertexwahn/rules_oidn#4]
The reproducer mentioned within #1 runs fine, but is looks that it does not produce any files:

```sh
PS P:\bounty\oidn\tests> bazel run --config=vs2022 //:example
[...]
Simple denoising example

Intel(R) Open Image Denoise 1.4.3@
  Compiler: Visual C++ Compiler 19.33.3163.0
  Build   : Debug
  Platform: Windows (64-bit)
  Tasking : TBB2021.9 TBB_header_interface_12090 TBB_lib_interface_12090
  Threads : 8 (affinitized)
  ISA     : AVX2
  Neural  : DNNL (oneDNN) 2.7.1

Filter: RT

```

It should produce "denoised.exr", ~but it does not.~

~No other file is produced.~

## Workaround

as a quick workaround I used ub 22.04, the file is produced there, though not at the location expected.

EDIT: same on windows

## Task

(this is essentially a bug, should be fixed. At minimum, document the location)

**Comment by Vertexwahn** [comment]
It works - the denoise.exr image is stored in bazel`s sandbox - if you want to have it outside you can provide now a command line argument:
bazel run --config=gcc11 //:example -- --filename=${HOME}/denoised_image.exr
