### ISSUE TITLE
[MAJOR] Replay/Rework Overall bazel Build

### ISSUE THREAD

**Issue by ghost** [Vertexwahn/rules_oidn#5]
This issue lists several task that attempt to fix
- #1 
---

- [x] #3
- (following list ordered by "highest estimated possibility of root-cause")
- [x] #7
  - [x] #9
- [x] #10
- [x] #8
- [x] #6
- (convenience stuff, but essentially a must have)
- [x] #4
- [x] #11

**Comment by Vertexwahn** [comment]
https://github.com/Vertexwahn/rules_oidn/issues/1 was solved
