### ISSUE TITLE
Use the recommended toolchain (clang)

### ISSUE THREAD

**Issue by ghost** [Vertexwahn/rules_oidn#6]
Just to be sure: use the toolchain that the oidn project recommends:

- clang

**Comment by Vertexwahn** [comment]
There is https://github.com/grailbio/bazel-toolchain - could be easily integrated and tested....

**Comment by ghost** [comment]
This did it for now

bazel run --config=clang14 //:example`

**Comment by Vertexwahn** [comment]
https://github.com/Vertexwahn/rules_oidn/issues/1 was solved
