### ISSUE TITLE
Why is 0001-Bazel-support.patch applied?

### ISSUE THREAD

**Issue by ghost** [Vertexwahn/rules_oidn#9]
Whys is `mkl_dnn` submodule-directory not used directly?

Instead , this patch is applied.

https://github.com/Vertexwahn/rules_oidn/blob/main/0001-Bazel-support.patch

(the source-tree/behaviour should be as close as possible to the original repo)

**Comment by Vertexwahn** [comment]
The patch is applied since Bazel assumes includes to be relative to the workspace - see https://bazel.build/docs/bazel-and-cpp#include-paths
